apiVersion: apps/v1
kind: Deployment
metadata:
  name: outsource-pc
  namespace: dev
spec:
  selector:
    matchLabels:
      app: outsource-pc
  replicas: 1
  template:
    metadata:
      labels:
        app: outsource-pc
    spec:
      containers:
        - name: outsource-pc
          image: harbor.yj2025.com/dev/outsource-pc:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 11112
          volumeMounts:
            - mountPath: /data/java/logs/
              name: cache-volume
          env:
            - name: redepoly
              value: "2020-08-07 02:17:27"
      imagePullSecrets:
        - name: harbor-secret
      volumes:
        - name: cache-volume
          emptyDir: {}
