apiVersion: apps/v1
kind: Deployment
metadata:
  name: mrp-api
  namespace: dev
spec:
  selector:
    matchLabels:
      app: mrp-api
  replicas: 1
  template:
    metadata:
      labels:
        app: mrp-api
    spec:
      containers:
        - name: mrp-api
          image: harbor.yj2025.com/dev/mrp-api:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 34001
          volumeMounts:
            - mountPath: /data/java/logs/
              name: cache-volume
          env:
            - name: redepoly
              value: "2020-08-05 14:33:15"
      imagePullSecrets:
        - name: harbor-secret
      volumes:
        - name: cache-volume
          emptyDir: {}
