apiVersion: apps/v1
kind: Deployment
metadata:
  name: crm-pc
  namespace: dev
spec:
  selector:
    matchLabels:
      app: crm-pc
  replicas: 1
  template:
    metadata:
      labels:
        app: crm-pc
    spec:
      containers:
        - name: crm-pc
          image: harbor.yj2025.com/dev/crm-pc:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 11002
          volumeMounts:
            - mountPath: /data/java/logs/
              name: cache-volume
          env:
            - name: redepoly
              value: "2020-08-05 11:51:52"
      imagePullSecrets:
        - name: harbor-secret
      volumes:
        - name: cache-volume
          emptyDir: {}
