apiVersion: apps/v1
kind: Deployment
metadata:
  name: manufacture-pc
  namespace: dev
spec:
  selector:
    matchLabels:
      app: manufacture-pc
  replicas: 1
  template:
    metadata:
      labels:
        app: manufacture-pc
    spec:
      containers:
        - name: manufacture-pc
          image: harbor.yj2025.com/dev/manufacture-pc:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 33002
          volumeMounts:
            - mountPath: /data/java/logs/
              name: cache-volume
          env:
            - name: redepoly
              value: "2020-08-05 11:43:33"
      imagePullSecrets:
        - name: harbor-secret
      volumes:
        - name: cache-volume
          emptyDir: {}
