apiVersion: apps/v1
kind: Deployment
metadata:
  name: ierp-front
  namespace: dev
spec:
  selector:
    matchLabels:
      app: ierp-front
  replicas: 1
  template:
    metadata:
      labels:
        app: ierp-front
    spec:
      containers:
        - name: ierp-front
          image: harbor.yj2025.com/dev/ierp-front:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8865
          volumeMounts:
            - mountPath: /data/java/logs/
              name: cache-volume
          env:
            - name: redepoly
              value: "2020-08-04 11:25:29"
      imagePullSecrets:
        - name: harbor-secret
      volumes:
        - name: cache-volume
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: ierp-front-service
  namespace: dev
spec:
  ports:
    - port: 80
      targetPort: 8865
      protocol: TCP
  type: NodePort
  selector:
    app: ierp-front
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ierp-front-ingress
  namespace: dev
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
    - secretName: yj2025-secret
      hosts:
        - dev.yj2025.com
  rules:
    - host: dev.yj2025.com
      http:
        paths:
          - path: /
            backend:
              serviceName: ierp-next-service
              servicePort: 80
          - path: /ierp
            backend:
              serviceName: ierp-front-service
              servicePort: 80
