apiVersion: apps/v1
kind: Deployment
metadata:
  name: development-pc
  namespace: dev
spec:
  selector:
    matchLabels:
      app: development-pc
  replicas: 1
  template:
    metadata:
      labels:
        app: development-pc
    spec:
      containers:
        - name: development-pc
          image: harbor.yj2025.com/dev/development-pc:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 31002
          volumeMounts:
            - mountPath: /data/java/logs/
              name: cache-volume
          env:
            - name: redepoly
              value: "2020-08-06 15:38:49"
      imagePullSecrets:
        - name: harbor-secret
      volumes:
        - name: cache-volume
          emptyDir: {}
