apiVersion: apps/v1
kind: Deployment
metadata:
  name: process-pc
  namespace: dev
spec:
  selector:
    matchLabels:
      app: process-pc
  replicas: 1
  template:
    metadata:
      labels:
        app: process-pc
    spec:
      containers:
        - name: process-pc
          image: harbor.yj2025.com/dev/process-pc:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 31006
              # 暴露相应的端口到node上
              hostPort: 31006
          volumeMounts:
            - mountPath: /data/java/logs/
              name: cache-volume
          env:
            - name: redepoly
              value: "2020-08-06 10:14:53"
      imagePullSecrets:
        - name: harbor-secret
      volumes:
        - name: cache-volume
          emptyDir: {}
