apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-supply-api
  namespace: dev
spec:
  selector:
    matchLabels:
      app: customer-supply-api
  replicas: 1
  template:
    metadata:
      labels:
        app: customer-supply-api
    spec:
      containers:
        - name: customer-supply-api
          image: harbor.yj2025.com/dev/customer-supply-api:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 11122
              # 暴露相应的端口到node上
              hostPort: 11122
          volumeMounts:
            - mountPath: /data/java/logs/
              name: cache-volume
          env:
            - name: redepoly
              value: "2020-08-06 10:20:55"
      imagePullSecrets:
        - name: harbor-secret
      volumes:
        - name: cache-volume
          emptyDir: {}
