apiVersion: apps/v1
kind: Deployment
metadata:
  name: spug
  namespace: default
spec:
  selector:
    matchLabels:
      app: spug
  replicas: 1
  template:
    metadata:
      labels:
        app: spug
    spec:
      containers:
        - name: spug
          image: registry.aliyuncs.com/openspug/spug
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /data
              name: spug-data
      nodeSelector:
        kubernetes.io/hostname: host217nfs
      volumes:
        - name: spug-data
          persistentVolumeClaim:
            claimName: spug-data-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spug-data-claim
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: spug-service
  namespace: default
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
  selector:
    app: spug
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: spug-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    # 该映射中包含websocket，需要指定websocket对应的service名字
    nginx.org/websocket-services: "spug-service"
spec:
  tls:
    - secretName: yj2025-secret
      hosts:
        - dev.yj2025.com
  rules:
    - host: dev.yj2025.com
      http:
        paths:
          - path: /
            backend:
              serviceName: spug-service
              servicePort: 80
