# 声明 一个全局可读可写的公共目录
apiVersion: v1
kind: PersistentVolume
metadata:
  name: public-storage-pv
  namespace: dev
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /data/nfs/public-storage
    server: 192.168.1.217
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: public-storage-pvc
  namespace: dev
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
