apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APP_NAME}
  namespace: ${PROFILE}
spec:
  selector:
    matchLabels:
      app: ${APP_NAME}
  replicas: 1
  template:
    metadata:
      labels:
        app: ${APP_NAME}
    spec:
      containers:
        - name: ${APP_NAME}
          image: ${REGISTRY_GROUP}/${PROFILE}/${APP_NAME}:${APP_VERSION}
          imagePullPolicy: Always
          ports:
            - containerPort: ${APP_PORT}
          volumeMounts:
            - mountPath: /www/ecworking-config-repo-tmp
              name: config-repo
      nodeName: node202
      imagePullSecrets:
        - name: harbor-secret
      volumes:
        - name: config-repo
          persistentVolumeClaim:
            claimName: config-repo-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-repo-claim
  namespace: ${PROFILE}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: "eureka-service"
  namespace: "${PROFILE}"
spec:
  ports:
    - port: 80
      targetPort: 3030
      protocol: TCP
      nodePort: 30303
  type: NodePort
  selector:
    app: "eureka-config-server"
#  clusterIP: 10.96.126.50 # 可指定也可不指定
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: eureka-ingress
  namespace: dev
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
    - secretName: yj2025-secret
      hosts:
        - eureka-dev.yj2025.com
  rules:
    - host: eureka-dev.yj2025.com
      http:
        paths:
          - path: /
            backend:
              serviceName: eureka-service
              servicePort: 80
