apiVersion: apps/v1
kind: Deployment
metadata:
  name: abcd-api
  namespace: dev
spec:
  selector:
    matchLabels:
      app: abcd-api
  replicas: 1
  template:
    metadata:
      labels:
        app: abcd-api
    spec:
      containers:
        - name: abcd-api
          image: harbor.yj2025.com/dev/abcd-api:1.1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8172
          volumeMounts:
            - mountPath: /data/java/logs/
              name: cache-volume
          env:
            - name: redepoly
              value: "2020-08-06 15:38:46"
      imagePullSecrets:
        - name: harbor-secret
      volumes:
        - name: cache-volume
          emptyDir: {}
