apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-api
  namespace: dev
spec:
  selector:
    matchLabels:
      app: code-api
  replicas: 1
  template:
    metadata:
      labels:
        app: code-api
    spec:
      containers:
        - name: code-api
          image: harbor.yj2025.com/dev/code-api:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8172
          volumeMounts:
            - mountPath: /data/java/logs/
              name: cache-volume
          env:
            - name: redepoly
              value: "2020-08-03 15:41:39"
      imagePullSecrets:
        - name: harbor-secret
      volumes:
        - name: cache-volume
          emptyDir: {}
