apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-authority-pc
  namespace: dev
spec:
  selector:
    matchLabels:
      app: data-authority-pc
  replicas: 1
  template:
    metadata:
      labels:
        app: data-authority-pc
    spec:
      containers:
        - name: data-authority-pc
          image: harbor.yj2025.com/dev/data-authority-pc:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 12580
              # 暴露相应的端口到node上
              hostPort: 12580
          volumeMounts:
            - mountPath: /data/java/logs/
              name: cache-volume
          env:
            - name: redepoly
              value: "2020-08-06 12:15:53"
      imagePullSecrets:
        - name: harbor-secret
      volumes:
        - name: cache-volume
          emptyDir: {}
