apiVersion: apps/v1
kind: Deployment
metadata:
  name: system-setting-pc
  namespace: dev
spec:
  selector:
    matchLabels:
      app: system-setting-pc
  replicas: 1
  template:
    metadata:
      labels:
        app: system-setting-pc
    spec:
      containers:
        - name: system-setting-pc
          image: harbor.yj2025.com/dev/system-setting-pc:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8112
          volumeMounts:
            - mountPath: /data/java/logs/
              name: cache-volume
          env:
            - name: redepoly
              value: "2020-08-04 16:23:04"
      imagePullSecrets:
        - name: harbor-secret
      volumes:
        - name: cache-volume
          emptyDir: {}
