apiVersion: apps/v1
kind: Deployment
metadata:
  name: qc-api
  namespace: dev
spec:
  selector:
    matchLabels:
      app: qc-api
  replicas: 1
  template:
    metadata:
      labels:
        app: qc-api
    spec:
      containers:
        - name: qc-api
          image: harbor.yj2025.com/dev/qc-api:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 11102
          volumeMounts:
            - mountPath: /data/java/logs/
              name: cache-volume
          env:
            - name: redepoly
              value: "2020-08-05 13:57:20"
      imagePullSecrets:
        - name: harbor-secret
      volumes:
        - name: cache-volume
          emptyDir: {}
