apiVersion: apps/v1
kind: Deployment
metadata:
  name: storehouse-api
  namespace: dev
spec:
  selector:
    matchLabels:
      app: storehouse-api
  replicas: 1
  template:
    metadata:
      labels:
        app: storehouse-api
    spec:
      containers:
        - name: storehouse-api
          image: harbor.yj2025.com/dev/storehouse-api:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 11112
          volumeMounts:
            - mountPath: /data/java/logs/
              name: cache-volume
          env:
            - name: redepoly
              value: "2020-08-06 15:32:17"
      imagePullSecrets:
        - name: harbor-secret
      volumes:
        - name: cache-volume
          emptyDir: {}
