apiVersion: apps/v1
kind: Deployment
metadata:
  name: manufacture-api
  namespace: dev
spec:
  selector:
    matchLabels:
      app: manufacture-api
  replicas: 1
  template:
    metadata:
      labels:
        app: manufacture-api
    spec:
      containers:
        - name: manufacture-api
          image: harbor.yj2025.com/dev/manufacture-api:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 33001
              # 暴露相应的端口到node上
              hostPort: 33001
          volumeMounts:
            - mountPath: /data/java/logs/
              name: cache-volume
          env:
            - name: redepoly
              value: "2020-08-06 12:11:53"
      imagePullSecrets:
        - name: harbor-secret
      volumes:
        - name: cache-volume
          emptyDir: {}
