apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-repo-claim
  namespace: yunji
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      release: config-repo

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: config-repo
  labels:
    release: config-repo
  namespace: yunji
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-a6589043
