apiVersion: apps/v1
kind: Deployment
metadata:
  name: proofing-api
  namespace: dev
spec:
  selector:
    matchLabels:
      app: proofing-api
  replicas: 1
  template:
    metadata:
      labels:
        app: proofing-api
    spec:
      containers:
        - name: proofing-api
          image: harbor.yj2025.com/dev/proofing-api:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 12221
              # 暴露相应的端口到node上
              hostPort: 12221
          volumeMounts:
            - mountPath: /data/java/logs/
              name: cache-volume
          env:
            - name: redepoly
              value: "2020-08-06 12:09:19"
      imagePullSecrets:
        - name: harbor-secret
      volumes:
        - name: cache-volume
          emptyDir: {}
