apiVersion: apps/v1
kind: Deployment
metadata:
  name: crm-api
  namespace: dev
spec:
  selector:
    matchLabels:
      app: crm-api
  replicas: 1
  template:
    metadata:
      labels:
        app: crm-api
    spec:
      containers:
        - name: crm-api
          image: harbor.yj2025.com/dev/crm-api:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 11001
              # 暴露相应的端口到node上
              hostPort: 11001
          volumeMounts:
            - mountPath: /data/java/logs/
              name: cache-volume
          env:
            - name: redepoly
              value: "2020-08-06 10:21:50"
      imagePullSecrets:
        - name: harbor-secret
      volumes:
        - name: cache-volume
          emptyDir: {}
