apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: public-storage-pvc
  namespace: yunji
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      release: public-storage-pv

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: public-storage-pv
  labels:
    release: public-storage-pv
  namespace: yunji
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-a6589043

---
apiVersion: v1
kind: Pod
metadata:
  name: public-storage-pod
  namespace: yunji
spec:
  containers:
    - name: public-storage-pod
      image: busybox
      command:
        - "/bin/sh"
      args:
        - "-c"
        - "touch /mnt/SUCCESS && exit 0 || exit 1"
      volumeMounts:
        - name: public-storage
          mountPath: "/mnt"
  restartPolicy: "Never"
  volumes:
    - name: public-storage
      persistentVolumeClaim:
        claimName: public-storage-pvc
