apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-storage-provider
  namespace: dev
spec:
  selector:
    matchLabels:
      app: file-storage-provider
  replicas: 1
  template:
    metadata:
      labels:
        app: file-storage-provider
    spec:
      containers:
        - name: file-storage-provider
          image: harbor.yj2025.com/dev/file-storage-provider:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8686
          volumeMounts:
            - mountPath: /data/java/logs/
              name: cache-volume
          env:
            - name: redepoly
              value: "2020-08-06 15:37:06"
      imagePullSecrets:
        - name: harbor-secret
      volumes:
        - name: cache-volume
          emptyDir: {}
