apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket-server
  namespace: dev
spec:
  selector:
    matchLabels:
      app: websocket-server
  replicas: 1
  template:
    metadata:
      labels:
        app: websocket-server
    spec:
      containers:
        - name: websocket-server
          image: harbor.yj2025.com/dev/websocket-server:1.0.0
          imagePullPolicy: Always
          ports:
            - name: websocket
              containerPort: 8066
              protocol: TCP
            - name: web
              containerPort: 20001
              protocol: TCP
          volumeMounts:
            - mountPath: /data/java/logs/
              name: cache-volume
          env:
            - name: redepoly
              value: "2020-08-06 15:32:14"
      imagePullSecrets:
        - name: harbor-secret
      volumes:
        - name: cache-volume
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: websocket-server-service
  namespace: dev
spec:
  ports:
    - name: websocket
      port: 8066
      targetPort: 8066
      protocol: TCP
  type: ClusterIP
  selector:
    app: websocket-server
