apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-storage-upload
  namespace: dev
spec:
  selector:
    matchLabels:
      app: file-storage-upload
  replicas: 1
  template:
    metadata:
      labels:
        app: file-storage-upload
    spec:
      containers:
        - name: file-storage-upload
          image: harbor.yj2025.com/dev/file-storage-upload:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8687
          volumeMounts:
            - mountPath: /data/java/logs/
              name: cache-volume
          env:
            - name: redepoly
              value: "2020-08-05 14:16:59"
      imagePullSecrets:
        - name: harbor-secret
      volumes:
        - name: cache-volume
          emptyDir: {}
