# 创建一个测试pvc ，测试nfs-provisioner的自动分配。并创建一个pod生成SUCCESS文件到挂载目录。
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-claim
  namespace: dev
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
  storageClassName: nfs-client
---
apiVersion: v1
kind: Pod
metadata:
  name: test-claim-pod
  namespace: dev
spec:
  containers:
    - name: test-claim-pod
      image: busybox
      command:
        - "/bin/sh"
      args:
        - "-c"
        - "touch /mnt/SUCCESS && exit 0 || exit 1"
      volumeMounts:
        - name: nfs-pvc
          mountPath: "/mnt"
  restartPolicy: "Never"
  volumes:
    - name: nfs-pvc
      persistentVolumeClaim:
        claimName: test-claim
